output "vpc_id" {
  description = "VPC ID"
  value       = module.vpc.vpc_id
}

output "public_subnet_ids" {
  description = "List of public subnet IDs"
  value       = module.vpc.public_subnet_ids
}

output "private_subnet_ids" {
  description = "List of private subnet IDs"
  value       = module.vpc.private_subnet_ids
}

output "nat_gateway_id" {
  description = "NAT Gateway ID"
  value       = module.nat_gw.nat_gateway_id
}

output "eip_id" {
  description = "Elastic IP Allocation ID"
  value       = module.eip.eip_id
}

output "rds_endpoint" {
  description = "RDS Endpoint"
  value       = module.rds.db_endpoint
}

output "bastion_public_ip" {
  description = "Public IP of the Bastion Host"
  value       = module.bastion.bastion_public_ip
}

output "alb_dns_name" {
  description = "The DNS name of the ALB"
  value       = module.alb.alb_dns_name
}

output "target_group_arn" {
  description = "ARN of the Target Group attached to ALB"
  value       = module.alb.target_group_arn
}

output "efs_id" {
  description = "EFS File System ID"
  value       = module.efs.efs_id
}

output "efs_sg_id" {
  description = "Security Group ID attached to EFS"
  value       = module.efs.efs_sg_id
}

output "asg_name" {
  description = "The name of the Auto Scaling Group"
  value       = module.asg.asg_name
}

output "wordpress_private_key_pem" {
  description = "The private key content generated by Terraform"
  value       = tls_private_key.wordpress_key.private_key_pem
  sensitive   = true
}

output "key_name" {
  description = "Name of the EC2 key pair"
  value       = aws_key_pair.wordpress_key.key_name
}

output "private_key_file" {
  description = "Path to the saved private key PEM file"
  value       = local_file.private_key_pem.filename
}

output "wordpress_sg_id" {
  description = "WordPress instance security group ID"
  value       = module.wordpress_sg.security_group_id
}
